# local_costmap:
#   global_frame: map
#   robot_base_frame: base_frame

#   update_frequency: 2.0 #2.0 old
#   publish_frequency: 1.0 #1.0 old
#   static_map: false
#   rolling_window: true
#   width: 6.0
#   height: 6.0
#   resolution: 0.05
#   # transform_tolerance: 0.5 #new
local_costmap:
  global_frame: map 
  robot_base_frame: base_frame

  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 0.5  

  static_map: false  
  rolling_window: true
  width: 3.0
  height: 3.0
  resolution: 0.05

#turtlebot3
# local_costmap:
#   global_frame: odom
#   robot_base_frame: base_footprint

#   update_frequency: 10.0
#   publish_frequency: 10.0
#   transform_tolerance: 0.5  

#   static_map: false  
#   rolling_window: true
#   width: 3
#   height: 3
#   resolution: 0.05
  
